// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tcnapi/exile/gate/v2/entities.proto

package gatev2

import (
	_ "github.com/tcncloud/sati-go/internal/genproto/tcnapi/exile/core/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallerState int32

const (
	CallerState_CALLER_STATE_UNAVALIABLE                    CallerState = 0
	CallerState_CALLER_STATE_IDLE                           CallerState = 1
	CallerState_CALLER_STATE_READY                          CallerState = 2
	CallerState_CALLER_STATE_HUNGUP                         CallerState = 3
	CallerState_CALLER_STATE_DESTROYED                      CallerState = 4
	CallerState_CALLER_STATE_PEERED                         CallerState = 5
	CallerState_CALLER_STATE_OUTBOUND_LOCKED                CallerState = 6
	CallerState_CALLER_STATE_OUTBOUND_PEERED                CallerState = 7
	CallerState_CALLER_STATE_PBX_POPUP_LOCKED               CallerState = 8
	CallerState_CALLER_STATE_VOICEMAIL                      CallerState = 9
	CallerState_CALLER_STATE_PEERED_WITH_CALL_ON_HOLD       CallerState = 10
	CallerState_CALLER_STATE_CALLBACK_SUSPENDED             CallerState = 11
	CallerState_CALLER_STATE_WARM_AGENT_TRANSFER_STARTED    CallerState = 12
	CallerState_CALLER_STATE_WARM_OUTBOUND_TRANSFER_STARTED CallerState = 13
	CallerState_CALLER_STATE_OUTBOUND_DIAL_TRANSFER_STARTED CallerState = 14
	CallerState_CALLER_STATE_PREPARED_TO_PEER               CallerState = 15
	CallerState_CALLER_STATE_WARM_SKILL_TRANSFER_PENDING    CallerState = 16
	// when the transfer starts for the peer
	CallerState_CALLER_STATE_CALLER_TRANSFER_PEER CallerState = 17
	// when the transfer starts for the destination caller
	CallerState_CALLER_STATE_CALLER_TRANSFER_MERGED_CALLER CallerState = 18
	// when the transfer is accepted and the agent leaves the transfer
	CallerState_CALLER_STATE_CALLER_PEERED CallerState = 19
)

// Enum value maps for CallerState.
var (
	CallerState_name = map[int32]string{
		0:  "CALLER_STATE_UNAVALIABLE",
		1:  "CALLER_STATE_IDLE",
		2:  "CALLER_STATE_READY",
		3:  "CALLER_STATE_HUNGUP",
		4:  "CALLER_STATE_DESTROYED",
		5:  "CALLER_STATE_PEERED",
		6:  "CALLER_STATE_OUTBOUND_LOCKED",
		7:  "CALLER_STATE_OUTBOUND_PEERED",
		8:  "CALLER_STATE_PBX_POPUP_LOCKED",
		9:  "CALLER_STATE_VOICEMAIL",
		10: "CALLER_STATE_PEERED_WITH_CALL_ON_HOLD",
		11: "CALLER_STATE_CALLBACK_SUSPENDED",
		12: "CALLER_STATE_WARM_AGENT_TRANSFER_STARTED",
		13: "CALLER_STATE_WARM_OUTBOUND_TRANSFER_STARTED",
		14: "CALLER_STATE_OUTBOUND_DIAL_TRANSFER_STARTED",
		15: "CALLER_STATE_PREPARED_TO_PEER",
		16: "CALLER_STATE_WARM_SKILL_TRANSFER_PENDING",
		17: "CALLER_STATE_CALLER_TRANSFER_PEER",
		18: "CALLER_STATE_CALLER_TRANSFER_MERGED_CALLER",
		19: "CALLER_STATE_CALLER_PEERED",
	}
	CallerState_value = map[string]int32{
		"CALLER_STATE_UNAVALIABLE":                    0,
		"CALLER_STATE_IDLE":                           1,
		"CALLER_STATE_READY":                          2,
		"CALLER_STATE_HUNGUP":                         3,
		"CALLER_STATE_DESTROYED":                      4,
		"CALLER_STATE_PEERED":                         5,
		"CALLER_STATE_OUTBOUND_LOCKED":                6,
		"CALLER_STATE_OUTBOUND_PEERED":                7,
		"CALLER_STATE_PBX_POPUP_LOCKED":               8,
		"CALLER_STATE_VOICEMAIL":                      9,
		"CALLER_STATE_PEERED_WITH_CALL_ON_HOLD":       10,
		"CALLER_STATE_CALLBACK_SUSPENDED":             11,
		"CALLER_STATE_WARM_AGENT_TRANSFER_STARTED":    12,
		"CALLER_STATE_WARM_OUTBOUND_TRANSFER_STARTED": 13,
		"CALLER_STATE_OUTBOUND_DIAL_TRANSFER_STARTED": 14,
		"CALLER_STATE_PREPARED_TO_PEER":               15,
		"CALLER_STATE_WARM_SKILL_TRANSFER_PENDING":    16,
		"CALLER_STATE_CALLER_TRANSFER_PEER":           17,
		"CALLER_STATE_CALLER_TRANSFER_MERGED_CALLER":  18,
		"CALLER_STATE_CALLER_PEERED":                  19,
	}
)

func (x CallerState) Enum() *CallerState {
	p := new(CallerState)
	*p = x
	return p
}

func (x CallerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallerState) Descriptor() protoreflect.EnumDescriptor {
	return file_tcnapi_exile_gate_v2_entities_proto_enumTypes[0].Descriptor()
}

func (CallerState) Type() protoreflect.EnumType {
	return &file_tcnapi_exile_gate_v2_entities_proto_enumTypes[0]
}

func (x CallerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallerState.Descriptor instead.
func (CallerState) EnumDescriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{0}
}

type CallType int32

const (
	// INBOUND should be default
	CallType_CALL_TYPE_INBOUND  CallType = 0
	CallType_CALL_TYPE_OUTBOUND CallType = 1
	CallType_CALL_TYPE_PREVIEW  CallType = 2
	CallType_CALL_TYPE_MANUAL   CallType = 3
	CallType_CALL_TYPE_MAC      CallType = 4
)

// Enum value maps for CallType.
var (
	CallType_name = map[int32]string{
		0: "CALL_TYPE_INBOUND",
		1: "CALL_TYPE_OUTBOUND",
		2: "CALL_TYPE_PREVIEW",
		3: "CALL_TYPE_MANUAL",
		4: "CALL_TYPE_MAC",
	}
	CallType_value = map[string]int32{
		"CALL_TYPE_INBOUND":  0,
		"CALL_TYPE_OUTBOUND": 1,
		"CALL_TYPE_PREVIEW":  2,
		"CALL_TYPE_MANUAL":   3,
		"CALL_TYPE_MAC":      4,
	}
)

func (x CallType) Enum() *CallType {
	p := new(CallType)
	*p = x
	return p
}

func (x CallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallType) Descriptor() protoreflect.EnumDescriptor {
	return file_tcnapi_exile_gate_v2_entities_proto_enumTypes[1].Descriptor()
}

func (CallType) Type() protoreflect.EnumType {
	return &file_tcnapi_exile_gate_v2_entities_proto_enumTypes[1]
}

func (x CallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallType.Descriptor instead.
func (CallType) EnumDescriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{1}
}

type AgentState int32

const (
	AgentState_AGENT_STATE_UNAVALIABLE                             AgentState = 0
	AgentState_AGENT_STATE_IDLE                                    AgentState = 1
	AgentState_AGENT_STATE_READY                                   AgentState = 2
	AgentState_AGENT_STATE_HUNGUP                                  AgentState = 3
	AgentState_AGENT_STATE_DESTROYED                               AgentState = 4
	AgentState_AGENT_STATE_PEERED                                  AgentState = 5
	AgentState_AGENT_STATE_PAUSED                                  AgentState = 6
	AgentState_AGENT_STATE_WRAPUP                                  AgentState = 7
	AgentState_AGENT_STATE_PREPARING_AFTER_IDLE                    AgentState = 8
	AgentState_AGENT_STATE_PREPARING_AFTER_WRAPUP                  AgentState = 9
	AgentState_AGENT_STATE_PREPARING_AFTER_PAUSE                   AgentState = 10
	AgentState_AGENT_STATE_PREPARING_AFTER_DIAL_CANCEL             AgentState = 11
	AgentState_AGENT_STATE_PREPARING_AFTER_PBX_REJECT              AgentState = 12
	AgentState_AGENT_STATE_PREPARING_AFTER_PBX_HANGUP              AgentState = 13
	AgentState_AGENT_STATE_PREPARING_AFTER_PBX_WAS_TAKEN           AgentState = 14
	AgentState_AGENT_STATE_PREPARING_AFTER_GUI_BUSY                AgentState = 15
	AgentState_AGENT_STATE_MANUAL_DIAL_PREPARED                    AgentState = 16
	AgentState_AGENT_STATE_PREVIEW_DIAL_PREPARED                   AgentState = 17
	AgentState_AGENT_STATE_MANUAL_DIAL_STARTED                     AgentState = 18
	AgentState_AGENT_STATE_PREVIEW_DIAL_STARTED                    AgentState = 19
	AgentState_AGENT_STATE_OUTBOUND_LOCKED                         AgentState = 20
	AgentState_AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_SOURCE      AgentState = 21
	AgentState_AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_DESTINATION AgentState = 22
	AgentState_AGENT_STATE_WARM_OUTBOUND_TRANSFER_STARTED          AgentState = 23
	AgentState_AGENT_STATE_WARM_OUTBOUND_TRANSFER_PEER_LOST        AgentState = 24
	AgentState_AGENT_STATE_PBX_POPUP_LOCKED                        AgentState = 25
	AgentState_AGENT_STATE_PEERED_WITH_CALL_ON_HOLD                AgentState = 26
	AgentState_AGENT_STATE_CALLBACK_RESUMING                       AgentState = 27
	AgentState_AGENT_STATE_GUI_BUSY                                AgentState = 28
	AgentState_AGENT_STATE_INTERCOM                                AgentState = 29
	AgentState_AGENT_STATE_INTERCOM_RINGING_SOURCE                 AgentState = 30
	AgentState_AGENT_STATE_INTERCOM_RINGING_DESTINATION            AgentState = 31
	AgentState_AGENT_STATE_WARM_OUTBOUND_TRANSFER_OUTBOUND_LOST    AgentState = 32
	AgentState_AGENT_STATE_PREPARED_TO_PEER                        AgentState = 33
	AgentState_AGENT_STATE_WARM_SKILL_TRANSFER_SOURCE_PENDING      AgentState = 34
	// when the transfer has started
	AgentState_AGENT_STATE_CALLER_TRANSFER_STARTED AgentState = 35
	// when the transfer is running and the peer hangs up
	AgentState_AGENT_STATE_CALLER_TRANSFER_LOST_PEER AgentState = 36
	// when the transfer is running and the dest caller hangs up
	AgentState_AGENT_STATE_CALLER_TRANSFER_LOST_MERGED_CALLER AgentState = 37
	// interim state for cold outbound transfer
	AgentState_AGENT_STATE_COLD_OUTBOUND_TRANSFER_STARTED AgentState = 38
	// interim state for cold agent transfer
	AgentState_AGENT_STATE_COLD_AGENT_TRANSFER_STARTED AgentState = 39
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0:  "AGENT_STATE_UNAVALIABLE",
		1:  "AGENT_STATE_IDLE",
		2:  "AGENT_STATE_READY",
		3:  "AGENT_STATE_HUNGUP",
		4:  "AGENT_STATE_DESTROYED",
		5:  "AGENT_STATE_PEERED",
		6:  "AGENT_STATE_PAUSED",
		7:  "AGENT_STATE_WRAPUP",
		8:  "AGENT_STATE_PREPARING_AFTER_IDLE",
		9:  "AGENT_STATE_PREPARING_AFTER_WRAPUP",
		10: "AGENT_STATE_PREPARING_AFTER_PAUSE",
		11: "AGENT_STATE_PREPARING_AFTER_DIAL_CANCEL",
		12: "AGENT_STATE_PREPARING_AFTER_PBX_REJECT",
		13: "AGENT_STATE_PREPARING_AFTER_PBX_HANGUP",
		14: "AGENT_STATE_PREPARING_AFTER_PBX_WAS_TAKEN",
		15: "AGENT_STATE_PREPARING_AFTER_GUI_BUSY",
		16: "AGENT_STATE_MANUAL_DIAL_PREPARED",
		17: "AGENT_STATE_PREVIEW_DIAL_PREPARED",
		18: "AGENT_STATE_MANUAL_DIAL_STARTED",
		19: "AGENT_STATE_PREVIEW_DIAL_STARTED",
		20: "AGENT_STATE_OUTBOUND_LOCKED",
		21: "AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_SOURCE",
		22: "AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_DESTINATION",
		23: "AGENT_STATE_WARM_OUTBOUND_TRANSFER_STARTED",
		24: "AGENT_STATE_WARM_OUTBOUND_TRANSFER_PEER_LOST",
		25: "AGENT_STATE_PBX_POPUP_LOCKED",
		26: "AGENT_STATE_PEERED_WITH_CALL_ON_HOLD",
		27: "AGENT_STATE_CALLBACK_RESUMING",
		28: "AGENT_STATE_GUI_BUSY",
		29: "AGENT_STATE_INTERCOM",
		30: "AGENT_STATE_INTERCOM_RINGING_SOURCE",
		31: "AGENT_STATE_INTERCOM_RINGING_DESTINATION",
		32: "AGENT_STATE_WARM_OUTBOUND_TRANSFER_OUTBOUND_LOST",
		33: "AGENT_STATE_PREPARED_TO_PEER",
		34: "AGENT_STATE_WARM_SKILL_TRANSFER_SOURCE_PENDING",
		35: "AGENT_STATE_CALLER_TRANSFER_STARTED",
		36: "AGENT_STATE_CALLER_TRANSFER_LOST_PEER",
		37: "AGENT_STATE_CALLER_TRANSFER_LOST_MERGED_CALLER",
		38: "AGENT_STATE_COLD_OUTBOUND_TRANSFER_STARTED",
		39: "AGENT_STATE_COLD_AGENT_TRANSFER_STARTED",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNAVALIABLE":                             0,
		"AGENT_STATE_IDLE":                                    1,
		"AGENT_STATE_READY":                                   2,
		"AGENT_STATE_HUNGUP":                                  3,
		"AGENT_STATE_DESTROYED":                               4,
		"AGENT_STATE_PEERED":                                  5,
		"AGENT_STATE_PAUSED":                                  6,
		"AGENT_STATE_WRAPUP":                                  7,
		"AGENT_STATE_PREPARING_AFTER_IDLE":                    8,
		"AGENT_STATE_PREPARING_AFTER_WRAPUP":                  9,
		"AGENT_STATE_PREPARING_AFTER_PAUSE":                   10,
		"AGENT_STATE_PREPARING_AFTER_DIAL_CANCEL":             11,
		"AGENT_STATE_PREPARING_AFTER_PBX_REJECT":              12,
		"AGENT_STATE_PREPARING_AFTER_PBX_HANGUP":              13,
		"AGENT_STATE_PREPARING_AFTER_PBX_WAS_TAKEN":           14,
		"AGENT_STATE_PREPARING_AFTER_GUI_BUSY":                15,
		"AGENT_STATE_MANUAL_DIAL_PREPARED":                    16,
		"AGENT_STATE_PREVIEW_DIAL_PREPARED":                   17,
		"AGENT_STATE_MANUAL_DIAL_STARTED":                     18,
		"AGENT_STATE_PREVIEW_DIAL_STARTED":                    19,
		"AGENT_STATE_OUTBOUND_LOCKED":                         20,
		"AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_SOURCE":      21,
		"AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_DESTINATION": 22,
		"AGENT_STATE_WARM_OUTBOUND_TRANSFER_STARTED":          23,
		"AGENT_STATE_WARM_OUTBOUND_TRANSFER_PEER_LOST":        24,
		"AGENT_STATE_PBX_POPUP_LOCKED":                        25,
		"AGENT_STATE_PEERED_WITH_CALL_ON_HOLD":                26,
		"AGENT_STATE_CALLBACK_RESUMING":                       27,
		"AGENT_STATE_GUI_BUSY":                                28,
		"AGENT_STATE_INTERCOM":                                29,
		"AGENT_STATE_INTERCOM_RINGING_SOURCE":                 30,
		"AGENT_STATE_INTERCOM_RINGING_DESTINATION":            31,
		"AGENT_STATE_WARM_OUTBOUND_TRANSFER_OUTBOUND_LOST":    32,
		"AGENT_STATE_PREPARED_TO_PEER":                        33,
		"AGENT_STATE_WARM_SKILL_TRANSFER_SOURCE_PENDING":      34,
		"AGENT_STATE_CALLER_TRANSFER_STARTED":                 35,
		"AGENT_STATE_CALLER_TRANSFER_LOST_PEER":               36,
		"AGENT_STATE_CALLER_TRANSFER_LOST_MERGED_CALLER":      37,
		"AGENT_STATE_COLD_OUTBOUND_TRANSFER_STARTED":          38,
		"AGENT_STATE_COLD_AGENT_TRANSFER_STARTED":             39,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_tcnapi_exile_gate_v2_entities_proto_enumTypes[2].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_tcnapi_exile_gate_v2_entities_proto_enumTypes[2]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{2}
}

type ExileTelephonyResult_Result int32

const (
	ExileTelephonyResult_RESULT_UNKNOWN                               ExileTelephonyResult_Result = 0
	ExileTelephonyResult_PENDING                                      ExileTelephonyResult_Result = 1000
	ExileTelephonyResult_ANSWERED                                     ExileTelephonyResult_Result = 2000
	ExileTelephonyResult_ANSWERED_LINKCALL                            ExileTelephonyResult_Result = 2100
	ExileTelephonyResult_ANSWERED_LINKCALL_ABANDONED                  ExileTelephonyResult_Result = 2110
	ExileTelephonyResult_ANSWERED_LINKCALL_AGENT_TALK                 ExileTelephonyResult_Result = 2120
	ExileTelephonyResult_ANSWERED_LINKCALL_SUSPENDED                  ExileTelephonyResult_Result = 2130
	ExileTelephonyResult_ANSWERED_LINKCALL_SUSPENDED_TIMEOUT          ExileTelephonyResult_Result = 2140
	ExileTelephonyResult_ANSWERED_LINKCALL_SUSPENDED_INBOUND_OVERRIDE ExileTelephonyResult_Result = 2150
	ExileTelephonyResult_ANSWERED_LINKCALL_SUSPENDED_RESUME           ExileTelephonyResult_Result = 2160
	ExileTelephonyResult_ANSWERED_HANGUP                              ExileTelephonyResult_Result = 2200
	ExileTelephonyResult_ANSWERED_VOICEMAIL                           ExileTelephonyResult_Result = 2300
	ExileTelephonyResult_MACHINE                                      ExileTelephonyResult_Result = 3000
	ExileTelephonyResult_MACHINE_DELIVERED                            ExileTelephonyResult_Result = 3100
	ExileTelephonyResult_MACHINE_HANGUP                               ExileTelephonyResult_Result = 3200
	ExileTelephonyResult_MACHINE_FAILED                               ExileTelephonyResult_Result = 3300
	ExileTelephonyResult_FAX                                          ExileTelephonyResult_Result = 4000
	ExileTelephonyResult_FAX_DELIVERED                                ExileTelephonyResult_Result = 4100
	ExileTelephonyResult_BUSY                                         ExileTelephonyResult_Result = 5000
	ExileTelephonyResult_NOANSWER                                     ExileTelephonyResult_Result = 6000
	ExileTelephonyResult_INVALID                                      ExileTelephonyResult_Result = 7000
	ExileTelephonyResult_INVALID_INCOMPLETE_NUMBER                    ExileTelephonyResult_Result = 7100
	ExileTelephonyResult_INVALID_UNKNOWN_PREFIX                       ExileTelephonyResult_Result = 7200
	ExileTelephonyResult_INVALID_UNKNOWN_PREFIX_NPA                   ExileTelephonyResult_Result = 7210
	ExileTelephonyResult_INVALID_UNKNOWN_PREFIX_NPANXX                ExileTelephonyResult_Result = 7220
	ExileTelephonyResult_INVALID_PREFIX_NPANXX_NOT_FOUND              ExileTelephonyResult_Result = 7230
	ExileTelephonyResult_INVALID_NO_ROUTE                             ExileTelephonyResult_Result = 7300
	ExileTelephonyResult_INVALID_DISCONNECTED                         ExileTelephonyResult_Result = 7400
	ExileTelephonyResult_INVALID_DISCONNECTED_SKIPTRACE               ExileTelephonyResult_Result = 7410
	ExileTelephonyResult_FAILED                                       ExileTelephonyResult_Result = 8000
	ExileTelephonyResult_FAILED_NO_LINES                              ExileTelephonyResult_Result = 8100
	ExileTelephonyResult_FAILED_CIRCUITS_BUSY                         ExileTelephonyResult_Result = 8200
	ExileTelephonyResult_FAILED_REFUSED                               ExileTelephonyResult_Result = 8300
	ExileTelephonyResult_FAILED_REFUSED_LEGAL                         ExileTelephonyResult_Result = 8310
	ExileTelephonyResult_FAILED_REFUSED_TECHNICAL                     ExileTelephonyResult_Result = 8320
	ExileTelephonyResult_FAILED_INTERNAL_ERROR                        ExileTelephonyResult_Result = 8330
	ExileTelephonyResult_FAILED_REFUSED_RETRIES_EXHAUSTED             ExileTelephonyResult_Result = 8340
	ExileTelephonyResult_FAILED_REFUSED_BLOCK                         ExileTelephonyResult_Result = 8350
	ExileTelephonyResult_CANCELED                                     ExileTelephonyResult_Result = 9000
	ExileTelephonyResult_CANCELED_TIMEZONE                            ExileTelephonyResult_Result = 9100
	ExileTelephonyResult_CANCELED_TIMEOUT                             ExileTelephonyResult_Result = 9200
	ExileTelephonyResult_CANCELED_DNCL                                ExileTelephonyResult_Result = 9300
	ExileTelephonyResult_CANCELED_CELLULAR_DNCL                       ExileTelephonyResult_Result = 9310
	ExileTelephonyResult_CANCELED_DNCL_ZIP_CODE                       ExileTelephonyResult_Result = 9320
	ExileTelephonyResult_CANCELED_MAX_RETRY                           ExileTelephonyResult_Result = 9400
	ExileTelephonyResult_CANCELED_INCOMPLETE_NUMBER                   ExileTelephonyResult_Result = 9500
)

// Enum value maps for ExileTelephonyResult_Result.
var (
	ExileTelephonyResult_Result_name = map[int32]string{
		0:    "RESULT_UNKNOWN",
		1000: "PENDING",
		2000: "ANSWERED",
		2100: "ANSWERED_LINKCALL",
		2110: "ANSWERED_LINKCALL_ABANDONED",
		2120: "ANSWERED_LINKCALL_AGENT_TALK",
		2130: "ANSWERED_LINKCALL_SUSPENDED",
		2140: "ANSWERED_LINKCALL_SUSPENDED_TIMEOUT",
		2150: "ANSWERED_LINKCALL_SUSPENDED_INBOUND_OVERRIDE",
		2160: "ANSWERED_LINKCALL_SUSPENDED_RESUME",
		2200: "ANSWERED_HANGUP",
		2300: "ANSWERED_VOICEMAIL",
		3000: "MACHINE",
		3100: "MACHINE_DELIVERED",
		3200: "MACHINE_HANGUP",
		3300: "MACHINE_FAILED",
		4000: "FAX",
		4100: "FAX_DELIVERED",
		5000: "BUSY",
		6000: "NOANSWER",
		7000: "INVALID",
		7100: "INVALID_INCOMPLETE_NUMBER",
		7200: "INVALID_UNKNOWN_PREFIX",
		7210: "INVALID_UNKNOWN_PREFIX_NPA",
		7220: "INVALID_UNKNOWN_PREFIX_NPANXX",
		7230: "INVALID_PREFIX_NPANXX_NOT_FOUND",
		7300: "INVALID_NO_ROUTE",
		7400: "INVALID_DISCONNECTED",
		7410: "INVALID_DISCONNECTED_SKIPTRACE",
		8000: "FAILED",
		8100: "FAILED_NO_LINES",
		8200: "FAILED_CIRCUITS_BUSY",
		8300: "FAILED_REFUSED",
		8310: "FAILED_REFUSED_LEGAL",
		8320: "FAILED_REFUSED_TECHNICAL",
		8330: "FAILED_INTERNAL_ERROR",
		8340: "FAILED_REFUSED_RETRIES_EXHAUSTED",
		8350: "FAILED_REFUSED_BLOCK",
		9000: "CANCELED",
		9100: "CANCELED_TIMEZONE",
		9200: "CANCELED_TIMEOUT",
		9300: "CANCELED_DNCL",
		9310: "CANCELED_CELLULAR_DNCL",
		9320: "CANCELED_DNCL_ZIP_CODE",
		9400: "CANCELED_MAX_RETRY",
		9500: "CANCELED_INCOMPLETE_NUMBER",
	}
	ExileTelephonyResult_Result_value = map[string]int32{
		"RESULT_UNKNOWN":                               0,
		"PENDING":                                      1000,
		"ANSWERED":                                     2000,
		"ANSWERED_LINKCALL":                            2100,
		"ANSWERED_LINKCALL_ABANDONED":                  2110,
		"ANSWERED_LINKCALL_AGENT_TALK":                 2120,
		"ANSWERED_LINKCALL_SUSPENDED":                  2130,
		"ANSWERED_LINKCALL_SUSPENDED_TIMEOUT":          2140,
		"ANSWERED_LINKCALL_SUSPENDED_INBOUND_OVERRIDE": 2150,
		"ANSWERED_LINKCALL_SUSPENDED_RESUME":           2160,
		"ANSWERED_HANGUP":                              2200,
		"ANSWERED_VOICEMAIL":                           2300,
		"MACHINE":                                      3000,
		"MACHINE_DELIVERED":                            3100,
		"MACHINE_HANGUP":                               3200,
		"MACHINE_FAILED":                               3300,
		"FAX":                                          4000,
		"FAX_DELIVERED":                                4100,
		"BUSY":                                         5000,
		"NOANSWER":                                     6000,
		"INVALID":                                      7000,
		"INVALID_INCOMPLETE_NUMBER":                    7100,
		"INVALID_UNKNOWN_PREFIX":                       7200,
		"INVALID_UNKNOWN_PREFIX_NPA":                   7210,
		"INVALID_UNKNOWN_PREFIX_NPANXX":                7220,
		"INVALID_PREFIX_NPANXX_NOT_FOUND":              7230,
		"INVALID_NO_ROUTE":                             7300,
		"INVALID_DISCONNECTED":                         7400,
		"INVALID_DISCONNECTED_SKIPTRACE":               7410,
		"FAILED":                                       8000,
		"FAILED_NO_LINES":                              8100,
		"FAILED_CIRCUITS_BUSY":                         8200,
		"FAILED_REFUSED":                               8300,
		"FAILED_REFUSED_LEGAL":                         8310,
		"FAILED_REFUSED_TECHNICAL":                     8320,
		"FAILED_INTERNAL_ERROR":                        8330,
		"FAILED_REFUSED_RETRIES_EXHAUSTED":             8340,
		"FAILED_REFUSED_BLOCK":                         8350,
		"CANCELED":                                     9000,
		"CANCELED_TIMEZONE":                            9100,
		"CANCELED_TIMEOUT":                             9200,
		"CANCELED_DNCL":                                9300,
		"CANCELED_CELLULAR_DNCL":                       9310,
		"CANCELED_DNCL_ZIP_CODE":                       9320,
		"CANCELED_MAX_RETRY":                           9400,
		"CANCELED_INCOMPLETE_NUMBER":                   9500,
	}
)

func (x ExileTelephonyResult_Result) Enum() *ExileTelephonyResult_Result {
	p := new(ExileTelephonyResult_Result)
	*p = x
	return p
}

func (x ExileTelephonyResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExileTelephonyResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_tcnapi_exile_gate_v2_entities_proto_enumTypes[3].Descriptor()
}

func (ExileTelephonyResult_Result) Type() protoreflect.EnumType {
	return &file_tcnapi_exile_gate_v2_entities_proto_enumTypes[3]
}

func (x ExileTelephonyResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExileTelephonyResult_Result.Descriptor instead.
func (ExileTelephonyResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{2, 0}
}

type ExileTelephonyResult_Status int32

const (
	ExileTelephonyResult_STATUS_UNKNOWN ExileTelephonyResult_Status = 0
	ExileTelephonyResult_SCHEDULED      ExileTelephonyResult_Status = 3100
	ExileTelephonyResult_RUNNING        ExileTelephonyResult_Status = 3200
	ExileTelephonyResult_COMPLETED      ExileTelephonyResult_Status = 3300
)

// Enum value maps for ExileTelephonyResult_Status.
var (
	ExileTelephonyResult_Status_name = map[int32]string{
		0:    "STATUS_UNKNOWN",
		3100: "SCHEDULED",
		3200: "RUNNING",
		3300: "COMPLETED",
	}
	ExileTelephonyResult_Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"SCHEDULED":      3100,
		"RUNNING":        3200,
		"COMPLETED":      3300,
	}
)

func (x ExileTelephonyResult_Status) Enum() *ExileTelephonyResult_Status {
	p := new(ExileTelephonyResult_Status)
	*p = x
	return p
}

func (x ExileTelephonyResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExileTelephonyResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tcnapi_exile_gate_v2_entities_proto_enumTypes[4].Descriptor()
}

func (ExileTelephonyResult_Status) Type() protoreflect.EnumType {
	return &file_tcnapi_exile_gate_v2_entities_proto_enumTypes[4]
}

func (x ExileTelephonyResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExileTelephonyResult_Status.Descriptor instead.
func (ExileTelephonyResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{2, 1}
}

type ExileAgentCall struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AgentCallSid             int64                  `protobuf:"varint,1,opt,name=agent_call_sid,json=agentCallSid,proto3" json:"agent_call_sid,omitempty"`
	CallSid                  int64                  `protobuf:"varint,2,opt,name=call_sid,json=callSid,proto3" json:"call_sid,omitempty"`
	CallType                 string                 `protobuf:"bytes,3,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	TalkDuration             int64                  `protobuf:"varint,4,opt,name=talk_duration,json=talkDuration,proto3" json:"talk_duration,omitempty"`
	CallWaitDuration         int64                  `protobuf:"varint,5,opt,name=call_wait_duration,json=callWaitDuration,proto3" json:"call_wait_duration,omitempty"`
	WrapUpDuration           int64                  `protobuf:"varint,6,opt,name=wrap_up_duration,json=wrapUpDuration,proto3" json:"wrap_up_duration,omitempty"`
	PauseDuration            int64                  `protobuf:"varint,7,opt,name=pause_duration,json=pauseDuration,proto3" json:"pause_duration,omitempty"`
	TransferDuration         int64                  `protobuf:"varint,8,opt,name=transfer_duration,json=transferDuration,proto3" json:"transfer_duration,omitempty"`
	ManualDuration           int64                  `protobuf:"varint,9,opt,name=manual_duration,json=manualDuration,proto3" json:"manual_duration,omitempty"`
	PreviewDuration          int64                  `protobuf:"varint,10,opt,name=preview_duration,json=previewDuration,proto3" json:"preview_duration,omitempty"`
	HoldDuration             int64                  `protobuf:"varint,11,opt,name=hold_duration,json=holdDuration,proto3" json:"hold_duration,omitempty"`
	AgentWaitDuration        int64                  `protobuf:"varint,12,opt,name=agent_wait_duration,json=agentWaitDuration,proto3" json:"agent_wait_duration,omitempty"`
	SuspendedDuration        int64                  `protobuf:"varint,13,opt,name=suspended_duration,json=suspendedDuration,proto3" json:"suspended_duration,omitempty"`
	ExternalTransferDuration int64                  `protobuf:"varint,14,opt,name=external_transfer_duration,json=externalTransferDuration,proto3" json:"external_transfer_duration,omitempty"`
	CreateTime               *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime               *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	OrgId                    string                 `protobuf:"bytes,17,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId                   string                 `protobuf:"bytes,18,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InternalKey              string                 `protobuf:"bytes,19,opt,name=internal_key,json=internalKey,proto3" json:"internal_key,omitempty"`
	TaskDataKeys             []*structpb.Value      `protobuf:"bytes,20,rep,name=task_data_keys,json=taskDataKeys,proto3" json:"task_data_keys,omitempty"`
	TaskDataValues           []*structpb.Value      `protobuf:"bytes,21,rep,name=task_data_values,json=taskDataValues,proto3" json:"task_data_values,omitempty"`
	PartnerAgentId           string                 `protobuf:"bytes,100,opt,name=partner_agent_id,json=partnerAgentId,proto3" json:"partner_agent_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExileAgentCall) Reset() {
	*x = ExileAgentCall{}
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExileAgentCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExileAgentCall) ProtoMessage() {}

func (x *ExileAgentCall) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExileAgentCall.ProtoReflect.Descriptor instead.
func (*ExileAgentCall) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{0}
}

func (x *ExileAgentCall) GetAgentCallSid() int64 {
	if x != nil {
		return x.AgentCallSid
	}
	return 0
}

func (x *ExileAgentCall) GetCallSid() int64 {
	if x != nil {
		return x.CallSid
	}
	return 0
}

func (x *ExileAgentCall) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *ExileAgentCall) GetTalkDuration() int64 {
	if x != nil {
		return x.TalkDuration
	}
	return 0
}

func (x *ExileAgentCall) GetCallWaitDuration() int64 {
	if x != nil {
		return x.CallWaitDuration
	}
	return 0
}

func (x *ExileAgentCall) GetWrapUpDuration() int64 {
	if x != nil {
		return x.WrapUpDuration
	}
	return 0
}

func (x *ExileAgentCall) GetPauseDuration() int64 {
	if x != nil {
		return x.PauseDuration
	}
	return 0
}

func (x *ExileAgentCall) GetTransferDuration() int64 {
	if x != nil {
		return x.TransferDuration
	}
	return 0
}

func (x *ExileAgentCall) GetManualDuration() int64 {
	if x != nil {
		return x.ManualDuration
	}
	return 0
}

func (x *ExileAgentCall) GetPreviewDuration() int64 {
	if x != nil {
		return x.PreviewDuration
	}
	return 0
}

func (x *ExileAgentCall) GetHoldDuration() int64 {
	if x != nil {
		return x.HoldDuration
	}
	return 0
}

func (x *ExileAgentCall) GetAgentWaitDuration() int64 {
	if x != nil {
		return x.AgentWaitDuration
	}
	return 0
}

func (x *ExileAgentCall) GetSuspendedDuration() int64 {
	if x != nil {
		return x.SuspendedDuration
	}
	return 0
}

func (x *ExileAgentCall) GetExternalTransferDuration() int64 {
	if x != nil {
		return x.ExternalTransferDuration
	}
	return 0
}

func (x *ExileAgentCall) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ExileAgentCall) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *ExileAgentCall) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ExileAgentCall) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExileAgentCall) GetInternalKey() string {
	if x != nil {
		return x.InternalKey
	}
	return ""
}

func (x *ExileAgentCall) GetTaskDataKeys() []*structpb.Value {
	if x != nil {
		return x.TaskDataKeys
	}
	return nil
}

func (x *ExileAgentCall) GetTaskDataValues() []*structpb.Value {
	if x != nil {
		return x.TaskDataValues
	}
	return nil
}

func (x *ExileAgentCall) GetPartnerAgentId() string {
	if x != nil {
		return x.PartnerAgentId
	}
	return ""
}

type StringField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringField) Reset() {
	*x = StringField{}
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringField) ProtoMessage() {}

func (x *StringField) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringField.ProtoReflect.Descriptor instead.
func (*StringField) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{1}
}

func (x *StringField) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type ExileTelephonyResult struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	CallSid        int64                       `protobuf:"varint,1,opt,name=call_sid,json=callSid,proto3" json:"call_sid,omitempty"`
	CallType       string                      `protobuf:"bytes,2,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	CreateTime     *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime     *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Status         ExileTelephonyResult_Status `protobuf:"varint,5,opt,name=status,proto3,enum=tcnapi.exile.gate.v2.ExileTelephonyResult_Status" json:"status,omitempty"`
	Result         ExileTelephonyResult_Result `protobuf:"varint,6,opt,name=result,proto3,enum=tcnapi.exile.gate.v2.ExileTelephonyResult_Result" json:"result,omitempty"`
	CallerId       string                      `protobuf:"bytes,7,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	PhoneNumber    string                      `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	StartTime      *timestamppb.Timestamp      `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp      `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DeliveryLength int64                       `protobuf:"varint,11,opt,name=delivery_length,json=deliveryLength,proto3" json:"delivery_length,omitempty"`
	LinkbackLength int64                       `protobuf:"varint,12,opt,name=linkback_length,json=linkbackLength,proto3" json:"linkback_length,omitempty"`
	PoolId         string                      `protobuf:"bytes,13,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	RecordId       string                      `protobuf:"bytes,14,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	ClientSid      int64                       `protobuf:"varint,15,opt,name=client_sid,json=clientSid,proto3" json:"client_sid,omitempty"`
	OrgId          string                      `protobuf:"bytes,16,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	InternalKey    string                      `protobuf:"bytes,17,opt,name=internal_key,json=internalKey,proto3" json:"internal_key,omitempty"`
	// string partner_agent_id = 100;
	TaskDataKeys   []*structpb.Value `protobuf:"bytes,20,rep,name=task_data_keys,json=taskDataKeys,proto3" json:"task_data_keys,omitempty"`
	TaskDataValues []*structpb.Value `protobuf:"bytes,21,rep,name=task_data_values,json=taskDataValues,proto3" json:"task_data_values,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExileTelephonyResult) Reset() {
	*x = ExileTelephonyResult{}
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExileTelephonyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExileTelephonyResult) ProtoMessage() {}

func (x *ExileTelephonyResult) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExileTelephonyResult.ProtoReflect.Descriptor instead.
func (*ExileTelephonyResult) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{2}
}

func (x *ExileTelephonyResult) GetCallSid() int64 {
	if x != nil {
		return x.CallSid
	}
	return 0
}

func (x *ExileTelephonyResult) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *ExileTelephonyResult) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ExileTelephonyResult) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *ExileTelephonyResult) GetStatus() ExileTelephonyResult_Status {
	if x != nil {
		return x.Status
	}
	return ExileTelephonyResult_STATUS_UNKNOWN
}

func (x *ExileTelephonyResult) GetResult() ExileTelephonyResult_Result {
	if x != nil {
		return x.Result
	}
	return ExileTelephonyResult_RESULT_UNKNOWN
}

func (x *ExileTelephonyResult) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *ExileTelephonyResult) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ExileTelephonyResult) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ExileTelephonyResult) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ExileTelephonyResult) GetDeliveryLength() int64 {
	if x != nil {
		return x.DeliveryLength
	}
	return 0
}

func (x *ExileTelephonyResult) GetLinkbackLength() int64 {
	if x != nil {
		return x.LinkbackLength
	}
	return 0
}

func (x *ExileTelephonyResult) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *ExileTelephonyResult) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ExileTelephonyResult) GetClientSid() int64 {
	if x != nil {
		return x.ClientSid
	}
	return 0
}

func (x *ExileTelephonyResult) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ExileTelephonyResult) GetInternalKey() string {
	if x != nil {
		return x.InternalKey
	}
	return ""
}

func (x *ExileTelephonyResult) GetTaskDataKeys() []*structpb.Value {
	if x != nil {
		return x.TaskDataKeys
	}
	return nil
}

func (x *ExileTelephonyResult) GetTaskDataValues() []*structpb.Value {
	if x != nil {
		return x.TaskDataValues
	}
	return nil
}

type ExileAgentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AgentCallResponseSid int64                  `protobuf:"varint,1,opt,name=agent_call_response_sid,json=agentCallResponseSid,proto3" json:"agent_call_response_sid,omitempty"`
	CallSid              int64                  `protobuf:"varint,2,opt,name=call_sid,json=callSid,proto3" json:"call_sid,omitempty"`
	CallType             string                 `protobuf:"bytes,3,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	ResponseKey          string                 `protobuf:"bytes,4,opt,name=response_key,json=responseKey,proto3" json:"response_key,omitempty"`
	ResponseValue        string                 `protobuf:"bytes,5,opt,name=response_value,json=responseValue,proto3" json:"response_value,omitempty"`
	CreateTime           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ClientSid            int64                  `protobuf:"varint,8,opt,name=client_sid,json=clientSid,proto3" json:"client_sid,omitempty"`
	OrgId                string                 `protobuf:"bytes,9,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	AgentSid             int64                  `protobuf:"varint,10,opt,name=agent_sid,json=agentSid,proto3" json:"agent_sid,omitempty"`
	UserId               string                 `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InternalKey          string                 `protobuf:"bytes,12,opt,name=internal_key,json=internalKey,proto3" json:"internal_key,omitempty"`
	PartnerAgentId       string                 `protobuf:"bytes,100,opt,name=partner_agent_id,json=partnerAgentId,proto3" json:"partner_agent_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExileAgentResponse) Reset() {
	*x = ExileAgentResponse{}
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExileAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExileAgentResponse) ProtoMessage() {}

func (x *ExileAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExileAgentResponse.ProtoReflect.Descriptor instead.
func (*ExileAgentResponse) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{3}
}

func (x *ExileAgentResponse) GetAgentCallResponseSid() int64 {
	if x != nil {
		return x.AgentCallResponseSid
	}
	return 0
}

func (x *ExileAgentResponse) GetCallSid() int64 {
	if x != nil {
		return x.CallSid
	}
	return 0
}

func (x *ExileAgentResponse) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *ExileAgentResponse) GetResponseKey() string {
	if x != nil {
		return x.ResponseKey
	}
	return ""
}

func (x *ExileAgentResponse) GetResponseValue() string {
	if x != nil {
		return x.ResponseValue
	}
	return ""
}

func (x *ExileAgentResponse) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ExileAgentResponse) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *ExileAgentResponse) GetClientSid() int64 {
	if x != nil {
		return x.ClientSid
	}
	return 0
}

func (x *ExileAgentResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ExileAgentResponse) GetAgentSid() int64 {
	if x != nil {
		return x.AgentSid
	}
	return 0
}

func (x *ExileAgentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExileAgentResponse) GetInternalKey() string {
	if x != nil {
		return x.InternalKey
	}
	return ""
}

func (x *ExileAgentResponse) GetPartnerAgentId() string {
	if x != nil {
		return x.PartnerAgentId
	}
	return ""
}

type AgentEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Channel          string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	OldState         AgentState             `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=tcnapi.exile.gate.v2.AgentState" json:"old_state,omitempty"`
	NewState         AgentState             `protobuf:"varint,3,opt,name=new_state,json=newState,proto3,enum=tcnapi.exile.gate.v2.AgentState" json:"new_state,omitempty"`
	StateChanged     int64                  `protobuf:"varint,4,opt,name=state_changed,json=stateChanged,proto3" json:"state_changed,omitempty"`
	TenantId         string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Server           string                 `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	AgentId          int64                  `protobuf:"varint,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	StateAge         int64                  `protobuf:"varint,8,opt,name=state_age,json=stateAge,proto3" json:"state_age,omitempty"`
	Timestamp        int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Timer            string                 `protobuf:"bytes,10,opt,name=timer,proto3" json:"timer,omitempty"`
	TimerValue       int64                  `protobuf:"varint,11,opt,name=timer_value,json=timerValue,proto3" json:"timer_value,omitempty"`
	HuntGroupId      int64                  `protobuf:"varint,12,opt,name=hunt_group_id,json=huntGroupId,proto3" json:"hunt_group_id,omitempty"`
	CurrentSessionId int64                  `protobuf:"varint,13,opt,name=current_session_id,json=currentSessionId,proto3" json:"current_session_id,omitempty"`
	Monitoring       bool                   `protobuf:"varint,15,opt,name=monitoring,proto3" json:"monitoring,omitempty"`
	CallsCount       int64                  `protobuf:"varint,16,opt,name=calls_count,json=callsCount,proto3" json:"calls_count,omitempty"`
	CallerId         string                 `protobuf:"bytes,17,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	Dnid             string                 `protobuf:"bytes,18,opt,name=dnid,proto3" json:"dnid,omitempty"`
	IntercomPeerId   int64                  `protobuf:"varint,19,opt,name=intercom_peer_id,json=intercomPeerId,proto3" json:"intercom_peer_id,omitempty"`
	PeerCallId       int64                  `protobuf:"varint,20,opt,name=peer_call_id,json=peerCallId,proto3" json:"peer_call_id,omitempty"`
	PeerCallType     CallType               `protobuf:"varint,21,opt,name=peer_call_type,json=peerCallType,proto3,enum=tcnapi.exile.gate.v2.CallType" json:"peer_call_type,omitempty"`
	Skills           map[string]int64       `protobuf:"bytes,22,rep,name=skills,proto3" json:"skills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AllSkills        map[string]int64       `protobuf:"bytes,23,rep,name=allSkills,proto3" json:"allSkills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastSipCode      int64                  `protobuf:"varint,24,opt,name=last_sip_code,json=lastSipCode,proto3" json:"last_sip_code,omitempty"`
	LastSipMessage   string                 `protobuf:"bytes,25,opt,name=last_sip_message,json=lastSipMessage,proto3" json:"last_sip_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{4}
}

func (x *AgentEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AgentEvent) GetOldState() AgentState {
	if x != nil {
		return x.OldState
	}
	return AgentState_AGENT_STATE_UNAVALIABLE
}

func (x *AgentEvent) GetNewState() AgentState {
	if x != nil {
		return x.NewState
	}
	return AgentState_AGENT_STATE_UNAVALIABLE
}

func (x *AgentEvent) GetStateChanged() int64 {
	if x != nil {
		return x.StateChanged
	}
	return 0
}

func (x *AgentEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AgentEvent) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *AgentEvent) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentEvent) GetStateAge() int64 {
	if x != nil {
		return x.StateAge
	}
	return 0
}

func (x *AgentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentEvent) GetTimer() string {
	if x != nil {
		return x.Timer
	}
	return ""
}

func (x *AgentEvent) GetTimerValue() int64 {
	if x != nil {
		return x.TimerValue
	}
	return 0
}

func (x *AgentEvent) GetHuntGroupId() int64 {
	if x != nil {
		return x.HuntGroupId
	}
	return 0
}

func (x *AgentEvent) GetCurrentSessionId() int64 {
	if x != nil {
		return x.CurrentSessionId
	}
	return 0
}

func (x *AgentEvent) GetMonitoring() bool {
	if x != nil {
		return x.Monitoring
	}
	return false
}

func (x *AgentEvent) GetCallsCount() int64 {
	if x != nil {
		return x.CallsCount
	}
	return 0
}

func (x *AgentEvent) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *AgentEvent) GetDnid() string {
	if x != nil {
		return x.Dnid
	}
	return ""
}

func (x *AgentEvent) GetIntercomPeerId() int64 {
	if x != nil {
		return x.IntercomPeerId
	}
	return 0
}

func (x *AgentEvent) GetPeerCallId() int64 {
	if x != nil {
		return x.PeerCallId
	}
	return 0
}

func (x *AgentEvent) GetPeerCallType() CallType {
	if x != nil {
		return x.PeerCallType
	}
	return CallType_CALL_TYPE_INBOUND
}

func (x *AgentEvent) GetSkills() map[string]int64 {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentEvent) GetAllSkills() map[string]int64 {
	if x != nil {
		return x.AllSkills
	}
	return nil
}

func (x *AgentEvent) GetLastSipCode() int64 {
	if x != nil {
		return x.LastSipCode
	}
	return 0
}

func (x *AgentEvent) GetLastSipMessage() string {
	if x != nil {
		return x.LastSipMessage
	}
	return ""
}

type CallerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	OldState      CallerState            `protobuf:"varint,2,opt,name=old_state,json=oldState,proto3,enum=tcnapi.exile.gate.v2.CallerState" json:"old_state,omitempty"`
	NewState      CallerState            `protobuf:"varint,3,opt,name=new_state,json=newState,proto3,enum=tcnapi.exile.gate.v2.CallerState" json:"new_state,omitempty"`
	StateChanged  int64                  `protobuf:"varint,4,opt,name=state_changed,json=stateChanged,proto3" json:"state_changed,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Server        string                 `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	CallId        int64                  `protobuf:"varint,7,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	StateAge      int64                  `protobuf:"varint,8,opt,name=state_age,json=stateAge,proto3" json:"state_age,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Timer         string                 `protobuf:"bytes,10,opt,name=timer,proto3" json:"timer,omitempty"`
	TimerValue    int64                  `protobuf:"varint,11,opt,name=timer_value,json=timerValue,proto3" json:"timer_value,omitempty"`
	HuntGroupId   int64                  `protobuf:"varint,12,opt,name=hunt_group_id,json=huntGroupId,proto3" json:"hunt_group_id,omitempty"`
	PeerId        int64                  `protobuf:"varint,13,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerSessionId int64                  `protobuf:"varint,14,opt,name=peer_session_id,json=peerSessionId,proto3" json:"peer_session_id,omitempty"`
	CallType      CallType               `protobuf:"varint,15,opt,name=call_type,json=callType,proto3,enum=tcnapi.exile.gate.v2.CallType" json:"call_type,omitempty"`
	Disconnecting bool                   `protobuf:"varint,16,opt,name=disconnecting,proto3" json:"disconnecting,omitempty"`
	ConfigFolder  string                 `protobuf:"bytes,17,opt,name=config_folder,json=configFolder,proto3" json:"config_folder,omitempty"`
	Counter       string                 `protobuf:"bytes,18,opt,name=counter,proto3" json:"counter,omitempty"`
	Skills        map[string]bool        `protobuf:"bytes,19,rep,name=skills,proto3" json:"skills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AllSkills     map[string]bool        `protobuf:"bytes,20,rep,name=allSkills,proto3" json:"allSkills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerEvent) Reset() {
	*x = CallerEvent{}
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerEvent) ProtoMessage() {}

func (x *CallerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_gate_v2_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerEvent.ProtoReflect.Descriptor instead.
func (*CallerEvent) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP(), []int{5}
}

func (x *CallerEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CallerEvent) GetOldState() CallerState {
	if x != nil {
		return x.OldState
	}
	return CallerState_CALLER_STATE_UNAVALIABLE
}

func (x *CallerEvent) GetNewState() CallerState {
	if x != nil {
		return x.NewState
	}
	return CallerState_CALLER_STATE_UNAVALIABLE
}

func (x *CallerEvent) GetStateChanged() int64 {
	if x != nil {
		return x.StateChanged
	}
	return 0
}

func (x *CallerEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CallerEvent) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *CallerEvent) GetCallId() int64 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *CallerEvent) GetStateAge() int64 {
	if x != nil {
		return x.StateAge
	}
	return 0
}

func (x *CallerEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CallerEvent) GetTimer() string {
	if x != nil {
		return x.Timer
	}
	return ""
}

func (x *CallerEvent) GetTimerValue() int64 {
	if x != nil {
		return x.TimerValue
	}
	return 0
}

func (x *CallerEvent) GetHuntGroupId() int64 {
	if x != nil {
		return x.HuntGroupId
	}
	return 0
}

func (x *CallerEvent) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *CallerEvent) GetPeerSessionId() int64 {
	if x != nil {
		return x.PeerSessionId
	}
	return 0
}

func (x *CallerEvent) GetCallType() CallType {
	if x != nil {
		return x.CallType
	}
	return CallType_CALL_TYPE_INBOUND
}

func (x *CallerEvent) GetDisconnecting() bool {
	if x != nil {
		return x.Disconnecting
	}
	return false
}

func (x *CallerEvent) GetConfigFolder() string {
	if x != nil {
		return x.ConfigFolder
	}
	return ""
}

func (x *CallerEvent) GetCounter() string {
	if x != nil {
		return x.Counter
	}
	return ""
}

func (x *CallerEvent) GetSkills() map[string]bool {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CallerEvent) GetAllSkills() map[string]bool {
	if x != nil {
		return x.AllSkills
	}
	return nil
}

var File_tcnapi_exile_gate_v2_entities_proto protoreflect.FileDescriptor

const file_tcnapi_exile_gate_v2_entities_proto_rawDesc = "" +
	"\n" +
	"#tcnapi/exile/gate/v2/entities.proto\x12\x14tcnapi.exile.gate.v2\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a#tcnapi/exile/core/v2/entities.proto\"\xcc\a\n" +
	"\x0eExileAgentCall\x12$\n" +
	"\x0eagent_call_sid\x18\x01 \x01(\x03R\fagentCallSid\x12\x19\n" +
	"\bcall_sid\x18\x02 \x01(\x03R\acallSid\x12\x1b\n" +
	"\tcall_type\x18\x03 \x01(\tR\bcallType\x12#\n" +
	"\rtalk_duration\x18\x04 \x01(\x03R\ftalkDuration\x12,\n" +
	"\x12call_wait_duration\x18\x05 \x01(\x03R\x10callWaitDuration\x12(\n" +
	"\x10wrap_up_duration\x18\x06 \x01(\x03R\x0ewrapUpDuration\x12%\n" +
	"\x0epause_duration\x18\a \x01(\x03R\rpauseDuration\x12+\n" +
	"\x11transfer_duration\x18\b \x01(\x03R\x10transferDuration\x12'\n" +
	"\x0fmanual_duration\x18\t \x01(\x03R\x0emanualDuration\x12)\n" +
	"\x10preview_duration\x18\n" +
	" \x01(\x03R\x0fpreviewDuration\x12#\n" +
	"\rhold_duration\x18\v \x01(\x03R\fholdDuration\x12.\n" +
	"\x13agent_wait_duration\x18\f \x01(\x03R\x11agentWaitDuration\x12-\n" +
	"\x12suspended_duration\x18\r \x01(\x03R\x11suspendedDuration\x12<\n" +
	"\x1aexternal_transfer_duration\x18\x0e \x01(\x03R\x18externalTransferDuration\x12;\n" +
	"\vcreate_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x15\n" +
	"\x06org_id\x18\x11 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x12 \x01(\tR\x06userId\x12!\n" +
	"\finternal_key\x18\x13 \x01(\tR\vinternalKey\x12<\n" +
	"\x0etask_data_keys\x18\x14 \x03(\v2\x16.google.protobuf.ValueR\ftaskDataKeys\x12@\n" +
	"\x10task_data_values\x18\x15 \x03(\v2\x16.google.protobuf.ValueR\x0etaskDataValues\x12(\n" +
	"\x10partner_agent_id\x18d \x01(\tR\x0epartnerAgentId\"2\n" +
	"\vStringField\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xf3\x10\n" +
	"\x14ExileTelephonyResult\x12\x19\n" +
	"\bcall_sid\x18\x01 \x01(\x03R\acallSid\x12\x1b\n" +
	"\tcall_type\x18\x02 \x01(\tR\bcallType\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12I\n" +
	"\x06status\x18\x05 \x01(\x0e21.tcnapi.exile.gate.v2.ExileTelephonyResult.StatusR\x06status\x12I\n" +
	"\x06result\x18\x06 \x01(\x0e21.tcnapi.exile.gate.v2.ExileTelephonyResult.ResultR\x06result\x12\x1b\n" +
	"\tcaller_id\x18\a \x01(\tR\bcallerId\x12!\n" +
	"\fphone_number\x18\b \x01(\tR\vphoneNumber\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12'\n" +
	"\x0fdelivery_length\x18\v \x01(\x03R\x0edeliveryLength\x12'\n" +
	"\x0flinkback_length\x18\f \x01(\x03R\x0elinkbackLength\x12\x17\n" +
	"\apool_id\x18\r \x01(\tR\x06poolId\x12\x1b\n" +
	"\trecord_id\x18\x0e \x01(\tR\brecordId\x12\x1d\n" +
	"\n" +
	"client_sid\x18\x0f \x01(\x03R\tclientSid\x12\x15\n" +
	"\x06org_id\x18\x10 \x01(\tR\x05orgId\x12!\n" +
	"\finternal_key\x18\x11 \x01(\tR\vinternalKey\x12<\n" +
	"\x0etask_data_keys\x18\x14 \x03(\v2\x16.google.protobuf.ValueR\ftaskDataKeys\x12@\n" +
	"\x10task_data_values\x18\x15 \x03(\v2\x16.google.protobuf.ValueR\x0etaskDataValues\"\xb3\t\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\f\n" +
	"\aPENDING\x10\xe8\a\x12\r\n" +
	"\bANSWERED\x10\xd0\x0f\x12\x16\n" +
	"\x11ANSWERED_LINKCALL\x10\xb4\x10\x12 \n" +
	"\x1bANSWERED_LINKCALL_ABANDONED\x10\xbe\x10\x12!\n" +
	"\x1cANSWERED_LINKCALL_AGENT_TALK\x10\xc8\x10\x12 \n" +
	"\x1bANSWERED_LINKCALL_SUSPENDED\x10\xd2\x10\x12(\n" +
	"#ANSWERED_LINKCALL_SUSPENDED_TIMEOUT\x10\xdc\x10\x121\n" +
	",ANSWERED_LINKCALL_SUSPENDED_INBOUND_OVERRIDE\x10\xe6\x10\x12'\n" +
	"\"ANSWERED_LINKCALL_SUSPENDED_RESUME\x10\xf0\x10\x12\x14\n" +
	"\x0fANSWERED_HANGUP\x10\x98\x11\x12\x17\n" +
	"\x12ANSWERED_VOICEMAIL\x10\xfc\x11\x12\f\n" +
	"\aMACHINE\x10\xb8\x17\x12\x16\n" +
	"\x11MACHINE_DELIVERED\x10\x9c\x18\x12\x13\n" +
	"\x0eMACHINE_HANGUP\x10\x80\x19\x12\x13\n" +
	"\x0eMACHINE_FAILED\x10\xe4\x19\x12\b\n" +
	"\x03FAX\x10\xa0\x1f\x12\x12\n" +
	"\rFAX_DELIVERED\x10\x84 \x12\t\n" +
	"\x04BUSY\x10\x88'\x12\r\n" +
	"\bNOANSWER\x10\xf0.\x12\f\n" +
	"\aINVALID\x10\xd86\x12\x1e\n" +
	"\x19INVALID_INCOMPLETE_NUMBER\x10\xbc7\x12\x1b\n" +
	"\x16INVALID_UNKNOWN_PREFIX\x10\xa08\x12\x1f\n" +
	"\x1aINVALID_UNKNOWN_PREFIX_NPA\x10\xaa8\x12\"\n" +
	"\x1dINVALID_UNKNOWN_PREFIX_NPANXX\x10\xb48\x12$\n" +
	"\x1fINVALID_PREFIX_NPANXX_NOT_FOUND\x10\xbe8\x12\x15\n" +
	"\x10INVALID_NO_ROUTE\x10\x849\x12\x19\n" +
	"\x14INVALID_DISCONNECTED\x10\xe89\x12#\n" +
	"\x1eINVALID_DISCONNECTED_SKIPTRACE\x10\xf29\x12\v\n" +
	"\x06FAILED\x10\xc0>\x12\x14\n" +
	"\x0fFAILED_NO_LINES\x10\xa4?\x12\x19\n" +
	"\x14FAILED_CIRCUITS_BUSY\x10\x88@\x12\x13\n" +
	"\x0eFAILED_REFUSED\x10\xec@\x12\x19\n" +
	"\x14FAILED_REFUSED_LEGAL\x10\xf6@\x12\x1d\n" +
	"\x18FAILED_REFUSED_TECHNICAL\x10\x80A\x12\x1a\n" +
	"\x15FAILED_INTERNAL_ERROR\x10\x8aA\x12%\n" +
	" FAILED_REFUSED_RETRIES_EXHAUSTED\x10\x94A\x12\x19\n" +
	"\x14FAILED_REFUSED_BLOCK\x10\x9eA\x12\r\n" +
	"\bCANCELED\x10\xa8F\x12\x16\n" +
	"\x11CANCELED_TIMEZONE\x10\x8cG\x12\x15\n" +
	"\x10CANCELED_TIMEOUT\x10\xf0G\x12\x12\n" +
	"\rCANCELED_DNCL\x10\xd4H\x12\x1b\n" +
	"\x16CANCELED_CELLULAR_DNCL\x10\xdeH\x12\x1b\n" +
	"\x16CANCELED_DNCL_ZIP_CODE\x10\xe8H\x12\x17\n" +
	"\x12CANCELED_MAX_RETRY\x10\xb8I\x12\x1f\n" +
	"\x1aCANCELED_INCOMPLETE_NUMBER\x10\x9cJ\"J\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x0e\n" +
	"\tSCHEDULED\x10\x9c\x18\x12\f\n" +
	"\aRUNNING\x10\x80\x19\x12\x0e\n" +
	"\tCOMPLETED\x10\xe4\x19\"\x80\x04\n" +
	"\x12ExileAgentResponse\x125\n" +
	"\x17agent_call_response_sid\x18\x01 \x01(\x03R\x14agentCallResponseSid\x12\x19\n" +
	"\bcall_sid\x18\x02 \x01(\x03R\acallSid\x12\x1b\n" +
	"\tcall_type\x18\x03 \x01(\tR\bcallType\x12!\n" +
	"\fresponse_key\x18\x04 \x01(\tR\vresponseKey\x12%\n" +
	"\x0eresponse_value\x18\x05 \x01(\tR\rresponseValue\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"client_sid\x18\b \x01(\x03R\tclientSid\x12\x15\n" +
	"\x06org_id\x18\t \x01(\tR\x05orgId\x12\x1b\n" +
	"\tagent_sid\x18\n" +
	" \x01(\x03R\bagentSid\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12!\n" +
	"\finternal_key\x18\f \x01(\tR\vinternalKey\x12(\n" +
	"\x10partner_agent_id\x18d \x01(\tR\x0epartnerAgentId\"\xbd\b\n" +
	"\n" +
	"AgentEvent\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12=\n" +
	"\told_state\x18\x02 \x01(\x0e2 .tcnapi.exile.gate.v2.AgentStateR\boldState\x12=\n" +
	"\tnew_state\x18\x03 \x01(\x0e2 .tcnapi.exile.gate.v2.AgentStateR\bnewState\x12#\n" +
	"\rstate_changed\x18\x04 \x01(\x03R\fstateChanged\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x16\n" +
	"\x06server\x18\x06 \x01(\tR\x06server\x12\x19\n" +
	"\bagent_id\x18\a \x01(\x03R\aagentId\x12\x1b\n" +
	"\tstate_age\x18\b \x01(\x03R\bstateAge\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05timer\x18\n" +
	" \x01(\tR\x05timer\x12\x1f\n" +
	"\vtimer_value\x18\v \x01(\x03R\n" +
	"timerValue\x12\"\n" +
	"\rhunt_group_id\x18\f \x01(\x03R\vhuntGroupId\x12,\n" +
	"\x12current_session_id\x18\r \x01(\x03R\x10currentSessionId\x12\x1e\n" +
	"\n" +
	"monitoring\x18\x0f \x01(\bR\n" +
	"monitoring\x12\x1f\n" +
	"\vcalls_count\x18\x10 \x01(\x03R\n" +
	"callsCount\x12\x1b\n" +
	"\tcaller_id\x18\x11 \x01(\tR\bcallerId\x12\x12\n" +
	"\x04dnid\x18\x12 \x01(\tR\x04dnid\x12(\n" +
	"\x10intercom_peer_id\x18\x13 \x01(\x03R\x0eintercomPeerId\x12 \n" +
	"\fpeer_call_id\x18\x14 \x01(\x03R\n" +
	"peerCallId\x12D\n" +
	"\x0epeer_call_type\x18\x15 \x01(\x0e2\x1e.tcnapi.exile.gate.v2.CallTypeR\fpeerCallType\x12D\n" +
	"\x06skills\x18\x16 \x03(\v2,.tcnapi.exile.gate.v2.AgentEvent.SkillsEntryR\x06skills\x12M\n" +
	"\tallSkills\x18\x17 \x03(\v2/.tcnapi.exile.gate.v2.AgentEvent.AllSkillsEntryR\tallSkills\x12\"\n" +
	"\rlast_sip_code\x18\x18 \x01(\x03R\vlastSipCode\x12(\n" +
	"\x10last_sip_message\x18\x19 \x01(\tR\x0elastSipMessage\x1a9\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eAllSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa3\a\n" +
	"\vCallerEvent\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12>\n" +
	"\told_state\x18\x02 \x01(\x0e2!.tcnapi.exile.gate.v2.CallerStateR\boldState\x12>\n" +
	"\tnew_state\x18\x03 \x01(\x0e2!.tcnapi.exile.gate.v2.CallerStateR\bnewState\x12#\n" +
	"\rstate_changed\x18\x04 \x01(\x03R\fstateChanged\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x16\n" +
	"\x06server\x18\x06 \x01(\tR\x06server\x12\x17\n" +
	"\acall_id\x18\a \x01(\x03R\x06callId\x12\x1b\n" +
	"\tstate_age\x18\b \x01(\x03R\bstateAge\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05timer\x18\n" +
	" \x01(\tR\x05timer\x12\x1f\n" +
	"\vtimer_value\x18\v \x01(\x03R\n" +
	"timerValue\x12\"\n" +
	"\rhunt_group_id\x18\f \x01(\x03R\vhuntGroupId\x12\x17\n" +
	"\apeer_id\x18\r \x01(\x03R\x06peerId\x12&\n" +
	"\x0fpeer_session_id\x18\x0e \x01(\x03R\rpeerSessionId\x12;\n" +
	"\tcall_type\x18\x0f \x01(\x0e2\x1e.tcnapi.exile.gate.v2.CallTypeR\bcallType\x12$\n" +
	"\rdisconnecting\x18\x10 \x01(\bR\rdisconnecting\x12#\n" +
	"\rconfig_folder\x18\x11 \x01(\tR\fconfigFolder\x12\x18\n" +
	"\acounter\x18\x12 \x01(\tR\acounter\x12E\n" +
	"\x06skills\x18\x13 \x03(\v2-.tcnapi.exile.gate.v2.CallerEvent.SkillsEntryR\x06skills\x12N\n" +
	"\tallSkills\x18\x14 \x03(\v20.tcnapi.exile.gate.v2.CallerEvent.AllSkillsEntryR\tallSkills\x1a9\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a<\n" +
	"\x0eAllSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01*\xd3\x05\n" +
	"\vCallerState\x12\x1c\n" +
	"\x18CALLER_STATE_UNAVALIABLE\x10\x00\x12\x15\n" +
	"\x11CALLER_STATE_IDLE\x10\x01\x12\x16\n" +
	"\x12CALLER_STATE_READY\x10\x02\x12\x17\n" +
	"\x13CALLER_STATE_HUNGUP\x10\x03\x12\x1a\n" +
	"\x16CALLER_STATE_DESTROYED\x10\x04\x12\x17\n" +
	"\x13CALLER_STATE_PEERED\x10\x05\x12 \n" +
	"\x1cCALLER_STATE_OUTBOUND_LOCKED\x10\x06\x12 \n" +
	"\x1cCALLER_STATE_OUTBOUND_PEERED\x10\a\x12!\n" +
	"\x1dCALLER_STATE_PBX_POPUP_LOCKED\x10\b\x12\x1a\n" +
	"\x16CALLER_STATE_VOICEMAIL\x10\t\x12)\n" +
	"%CALLER_STATE_PEERED_WITH_CALL_ON_HOLD\x10\n" +
	"\x12#\n" +
	"\x1fCALLER_STATE_CALLBACK_SUSPENDED\x10\v\x12,\n" +
	"(CALLER_STATE_WARM_AGENT_TRANSFER_STARTED\x10\f\x12/\n" +
	"+CALLER_STATE_WARM_OUTBOUND_TRANSFER_STARTED\x10\r\x12/\n" +
	"+CALLER_STATE_OUTBOUND_DIAL_TRANSFER_STARTED\x10\x0e\x12!\n" +
	"\x1dCALLER_STATE_PREPARED_TO_PEER\x10\x0f\x12,\n" +
	"(CALLER_STATE_WARM_SKILL_TRANSFER_PENDING\x10\x10\x12%\n" +
	"!CALLER_STATE_CALLER_TRANSFER_PEER\x10\x11\x12.\n" +
	"*CALLER_STATE_CALLER_TRANSFER_MERGED_CALLER\x10\x12\x12\x1e\n" +
	"\x1aCALLER_STATE_CALLER_PEERED\x10\x13*y\n" +
	"\bCallType\x12\x15\n" +
	"\x11CALL_TYPE_INBOUND\x10\x00\x12\x16\n" +
	"\x12CALL_TYPE_OUTBOUND\x10\x01\x12\x15\n" +
	"\x11CALL_TYPE_PREVIEW\x10\x02\x12\x14\n" +
	"\x10CALL_TYPE_MANUAL\x10\x03\x12\x11\n" +
	"\rCALL_TYPE_MAC\x10\x04*\x97\f\n" +
	"\n" +
	"AgentState\x12\x1b\n" +
	"\x17AGENT_STATE_UNAVALIABLE\x10\x00\x12\x14\n" +
	"\x10AGENT_STATE_IDLE\x10\x01\x12\x15\n" +
	"\x11AGENT_STATE_READY\x10\x02\x12\x16\n" +
	"\x12AGENT_STATE_HUNGUP\x10\x03\x12\x19\n" +
	"\x15AGENT_STATE_DESTROYED\x10\x04\x12\x16\n" +
	"\x12AGENT_STATE_PEERED\x10\x05\x12\x16\n" +
	"\x12AGENT_STATE_PAUSED\x10\x06\x12\x16\n" +
	"\x12AGENT_STATE_WRAPUP\x10\a\x12$\n" +
	" AGENT_STATE_PREPARING_AFTER_IDLE\x10\b\x12&\n" +
	"\"AGENT_STATE_PREPARING_AFTER_WRAPUP\x10\t\x12%\n" +
	"!AGENT_STATE_PREPARING_AFTER_PAUSE\x10\n" +
	"\x12+\n" +
	"'AGENT_STATE_PREPARING_AFTER_DIAL_CANCEL\x10\v\x12*\n" +
	"&AGENT_STATE_PREPARING_AFTER_PBX_REJECT\x10\f\x12*\n" +
	"&AGENT_STATE_PREPARING_AFTER_PBX_HANGUP\x10\r\x12-\n" +
	")AGENT_STATE_PREPARING_AFTER_PBX_WAS_TAKEN\x10\x0e\x12(\n" +
	"$AGENT_STATE_PREPARING_AFTER_GUI_BUSY\x10\x0f\x12$\n" +
	" AGENT_STATE_MANUAL_DIAL_PREPARED\x10\x10\x12%\n" +
	"!AGENT_STATE_PREVIEW_DIAL_PREPARED\x10\x11\x12#\n" +
	"\x1fAGENT_STATE_MANUAL_DIAL_STARTED\x10\x12\x12$\n" +
	" AGENT_STATE_PREVIEW_DIAL_STARTED\x10\x13\x12\x1f\n" +
	"\x1bAGENT_STATE_OUTBOUND_LOCKED\x10\x14\x122\n" +
	".AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_SOURCE\x10\x15\x127\n" +
	"3AGENT_STATE_WARM_AGENT_TRANSFER_STARTED_DESTINATION\x10\x16\x12.\n" +
	"*AGENT_STATE_WARM_OUTBOUND_TRANSFER_STARTED\x10\x17\x120\n" +
	",AGENT_STATE_WARM_OUTBOUND_TRANSFER_PEER_LOST\x10\x18\x12 \n" +
	"\x1cAGENT_STATE_PBX_POPUP_LOCKED\x10\x19\x12(\n" +
	"$AGENT_STATE_PEERED_WITH_CALL_ON_HOLD\x10\x1a\x12!\n" +
	"\x1dAGENT_STATE_CALLBACK_RESUMING\x10\x1b\x12\x18\n" +
	"\x14AGENT_STATE_GUI_BUSY\x10\x1c\x12\x18\n" +
	"\x14AGENT_STATE_INTERCOM\x10\x1d\x12'\n" +
	"#AGENT_STATE_INTERCOM_RINGING_SOURCE\x10\x1e\x12,\n" +
	"(AGENT_STATE_INTERCOM_RINGING_DESTINATION\x10\x1f\x124\n" +
	"0AGENT_STATE_WARM_OUTBOUND_TRANSFER_OUTBOUND_LOST\x10 \x12 \n" +
	"\x1cAGENT_STATE_PREPARED_TO_PEER\x10!\x122\n" +
	".AGENT_STATE_WARM_SKILL_TRANSFER_SOURCE_PENDING\x10\"\x12'\n" +
	"#AGENT_STATE_CALLER_TRANSFER_STARTED\x10#\x12)\n" +
	"%AGENT_STATE_CALLER_TRANSFER_LOST_PEER\x10$\x122\n" +
	".AGENT_STATE_CALLER_TRANSFER_LOST_MERGED_CALLER\x10%\x12.\n" +
	"*AGENT_STATE_COLD_OUTBOUND_TRANSFER_STARTED\x10&\x12+\n" +
	"'AGENT_STATE_COLD_AGENT_TRANSFER_STARTED\x10'B\xf4\x01\n" +
	"\x18com.tcnapi.exile.gate.v2B\rEntitiesProtoP\x01ZVgithub.com/tcncloud/sati-go/internal/genproto/tcnapi/exile/gate/v2;gatev2\xa2\x02\x03TEG\xaa\x02\x14Tcnapi.Exile.Gate.V2\xca\x02\x14Tcnapi\\Exile\\Gate\\V2\xe2\x02 Tcnapi\\Exile\\Gate\\V2\\GPBMetadata\xea\x02\x17Tcnapi::Exile::Gate::V2b\x06proto3"

var (
	file_tcnapi_exile_gate_v2_entities_proto_rawDescOnce sync.Once
	file_tcnapi_exile_gate_v2_entities_proto_rawDescData []byte
)

func file_tcnapi_exile_gate_v2_entities_proto_rawDescGZIP() []byte {
	file_tcnapi_exile_gate_v2_entities_proto_rawDescOnce.Do(func() {
		file_tcnapi_exile_gate_v2_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tcnapi_exile_gate_v2_entities_proto_rawDesc), len(file_tcnapi_exile_gate_v2_entities_proto_rawDesc)))
	})
	return file_tcnapi_exile_gate_v2_entities_proto_rawDescData
}

var file_tcnapi_exile_gate_v2_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_tcnapi_exile_gate_v2_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tcnapi_exile_gate_v2_entities_proto_goTypes = []any{
	(CallerState)(0),                 // 0: tcnapi.exile.gate.v2.CallerState
	(CallType)(0),                    // 1: tcnapi.exile.gate.v2.CallType
	(AgentState)(0),                  // 2: tcnapi.exile.gate.v2.AgentState
	(ExileTelephonyResult_Result)(0), // 3: tcnapi.exile.gate.v2.ExileTelephonyResult.Result
	(ExileTelephonyResult_Status)(0), // 4: tcnapi.exile.gate.v2.ExileTelephonyResult.Status
	(*ExileAgentCall)(nil),           // 5: tcnapi.exile.gate.v2.ExileAgentCall
	(*StringField)(nil),              // 6: tcnapi.exile.gate.v2.StringField
	(*ExileTelephonyResult)(nil),     // 7: tcnapi.exile.gate.v2.ExileTelephonyResult
	(*ExileAgentResponse)(nil),       // 8: tcnapi.exile.gate.v2.ExileAgentResponse
	(*AgentEvent)(nil),               // 9: tcnapi.exile.gate.v2.AgentEvent
	(*CallerEvent)(nil),              // 10: tcnapi.exile.gate.v2.CallerEvent
	nil,                              // 11: tcnapi.exile.gate.v2.AgentEvent.SkillsEntry
	nil,                              // 12: tcnapi.exile.gate.v2.AgentEvent.AllSkillsEntry
	nil,                              // 13: tcnapi.exile.gate.v2.CallerEvent.SkillsEntry
	nil,                              // 14: tcnapi.exile.gate.v2.CallerEvent.AllSkillsEntry
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*structpb.Value)(nil),           // 16: google.protobuf.Value
}
var file_tcnapi_exile_gate_v2_entities_proto_depIdxs = []int32{
	15, // 0: tcnapi.exile.gate.v2.ExileAgentCall.create_time:type_name -> google.protobuf.Timestamp
	15, // 1: tcnapi.exile.gate.v2.ExileAgentCall.update_time:type_name -> google.protobuf.Timestamp
	16, // 2: tcnapi.exile.gate.v2.ExileAgentCall.task_data_keys:type_name -> google.protobuf.Value
	16, // 3: tcnapi.exile.gate.v2.ExileAgentCall.task_data_values:type_name -> google.protobuf.Value
	15, // 4: tcnapi.exile.gate.v2.ExileTelephonyResult.create_time:type_name -> google.protobuf.Timestamp
	15, // 5: tcnapi.exile.gate.v2.ExileTelephonyResult.update_time:type_name -> google.protobuf.Timestamp
	4,  // 6: tcnapi.exile.gate.v2.ExileTelephonyResult.status:type_name -> tcnapi.exile.gate.v2.ExileTelephonyResult.Status
	3,  // 7: tcnapi.exile.gate.v2.ExileTelephonyResult.result:type_name -> tcnapi.exile.gate.v2.ExileTelephonyResult.Result
	15, // 8: tcnapi.exile.gate.v2.ExileTelephonyResult.start_time:type_name -> google.protobuf.Timestamp
	15, // 9: tcnapi.exile.gate.v2.ExileTelephonyResult.end_time:type_name -> google.protobuf.Timestamp
	16, // 10: tcnapi.exile.gate.v2.ExileTelephonyResult.task_data_keys:type_name -> google.protobuf.Value
	16, // 11: tcnapi.exile.gate.v2.ExileTelephonyResult.task_data_values:type_name -> google.protobuf.Value
	15, // 12: tcnapi.exile.gate.v2.ExileAgentResponse.create_time:type_name -> google.protobuf.Timestamp
	15, // 13: tcnapi.exile.gate.v2.ExileAgentResponse.update_time:type_name -> google.protobuf.Timestamp
	2,  // 14: tcnapi.exile.gate.v2.AgentEvent.old_state:type_name -> tcnapi.exile.gate.v2.AgentState
	2,  // 15: tcnapi.exile.gate.v2.AgentEvent.new_state:type_name -> tcnapi.exile.gate.v2.AgentState
	1,  // 16: tcnapi.exile.gate.v2.AgentEvent.peer_call_type:type_name -> tcnapi.exile.gate.v2.CallType
	11, // 17: tcnapi.exile.gate.v2.AgentEvent.skills:type_name -> tcnapi.exile.gate.v2.AgentEvent.SkillsEntry
	12, // 18: tcnapi.exile.gate.v2.AgentEvent.allSkills:type_name -> tcnapi.exile.gate.v2.AgentEvent.AllSkillsEntry
	0,  // 19: tcnapi.exile.gate.v2.CallerEvent.old_state:type_name -> tcnapi.exile.gate.v2.CallerState
	0,  // 20: tcnapi.exile.gate.v2.CallerEvent.new_state:type_name -> tcnapi.exile.gate.v2.CallerState
	1,  // 21: tcnapi.exile.gate.v2.CallerEvent.call_type:type_name -> tcnapi.exile.gate.v2.CallType
	13, // 22: tcnapi.exile.gate.v2.CallerEvent.skills:type_name -> tcnapi.exile.gate.v2.CallerEvent.SkillsEntry
	14, // 23: tcnapi.exile.gate.v2.CallerEvent.allSkills:type_name -> tcnapi.exile.gate.v2.CallerEvent.AllSkillsEntry
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_tcnapi_exile_gate_v2_entities_proto_init() }
func file_tcnapi_exile_gate_v2_entities_proto_init() {
	if File_tcnapi_exile_gate_v2_entities_proto != nil {
		return
	}
	file_tcnapi_exile_gate_v2_entities_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcnapi_exile_gate_v2_entities_proto_rawDesc), len(file_tcnapi_exile_gate_v2_entities_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tcnapi_exile_gate_v2_entities_proto_goTypes,
		DependencyIndexes: file_tcnapi_exile_gate_v2_entities_proto_depIdxs,
		EnumInfos:         file_tcnapi_exile_gate_v2_entities_proto_enumTypes,
		MessageInfos:      file_tcnapi_exile_gate_v2_entities_proto_msgTypes,
	}.Build()
	File_tcnapi_exile_gate_v2_entities_proto = out.File
	file_tcnapi_exile_gate_v2_entities_proto_goTypes = nil
	file_tcnapi_exile_gate_v2_entities_proto_depIdxs = nil
}
