// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright 2024 TCN Inc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: tcnapi/exile/core/v2/entities.proto

// This package contains the core entities for the Exile system.

package corev2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pool_PoolStatus int32

const (
	Pool_READY         Pool_PoolStatus = 0
	Pool_NOT_READY     Pool_PoolStatus = 1
	Pool_NOT_AVAILABLE Pool_PoolStatus = 1 // velosidy name this NOT_AVAILABLE
	Pool_BUSY          Pool_PoolStatus = 2
)

// Enum value maps for Pool_PoolStatus.
var (
	Pool_PoolStatus_name = map[int32]string{
		0: "READY",
		1: "NOT_READY",
		// Duplicate value: 1: "NOT_AVAILABLE",
		2: "BUSY",
	}
	Pool_PoolStatus_value = map[string]int32{
		"READY":         0,
		"NOT_READY":     1,
		"NOT_AVAILABLE": 1,
		"BUSY":          2,
	}
)

func (x Pool_PoolStatus) Enum() *Pool_PoolStatus {
	p := new(Pool_PoolStatus)
	*p = x
	return p
}

func (x Pool_PoolStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pool_PoolStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tcnapi_exile_core_v2_entities_proto_enumTypes[0].Descriptor()
}

func (Pool_PoolStatus) Type() protoreflect.EnumType {
	return &file_tcnapi_exile_core_v2_entities_proto_enumTypes[0]
}

func (x Pool_PoolStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pool_PoolStatus.Descriptor instead.
func (Pool_PoolStatus) EnumDescriptor() ([]byte, []int) {
	return file_tcnapi_exile_core_v2_entities_proto_rawDescGZIP(), []int{0, 0}
}

type Filter_Operator int32

const (
	Filter_EQUAL Filter_Operator = 0
)

// Enum value maps for Filter_Operator.
var (
	Filter_Operator_name = map[int32]string{
		0: "EQUAL",
	}
	Filter_Operator_value = map[string]int32{
		"EQUAL": 0,
	}
)

func (x Filter_Operator) Enum() *Filter_Operator {
	p := new(Filter_Operator)
	*p = x
	return p
}

func (x Filter_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_tcnapi_exile_core_v2_entities_proto_enumTypes[1].Descriptor()
}

func (Filter_Operator) Type() protoreflect.EnumType {
	return &file_tcnapi_exile_core_v2_entities_proto_enumTypes[1]
}

func (x Filter_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter_Operator.Descriptor instead.
func (Filter_Operator) EnumDescriptor() ([]byte, []int) {
	return file_tcnapi_exile_core_v2_entities_proto_rawDescGZIP(), []int{3, 0}
}

type Pool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        Pool_PoolStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=tcnapi.exile.core.v2.Pool_PoolStatus" json:"status,omitempty"`
	RecordCount   int64                  `protobuf:"varint,4,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_core_v2_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Pool) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *Pool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pool) GetStatus() Pool_PoolStatus {
	if x != nil {
		return x.Status
	}
	return Pool_READY
}

func (x *Pool) GetRecordCount() int64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

type Record struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PoolId            string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	RecordId          string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	JsonRecordPayload string                 `protobuf:"bytes,3,opt,name=json_record_payload,json=jsonRecordPayload,proto3" json:"json_record_payload,omitempty"` // json serialized record
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_core_v2_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *Record) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Record) GetJsonRecordPayload() string {
	if x != nil {
		return x.JsonRecordPayload
	}
	return ""
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	RecordId      string                 `protobuf:"bytes,4,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	FieldName     string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldValue    string                 `protobuf:"bytes,2,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_core_v2_entities_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *Field) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Field) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *Field) GetFieldValue() string {
	if x != nil {
		return x.FieldValue
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Operator      Filter_Operator        `protobuf:"varint,3,opt,name=operator,proto3,enum=tcnapi.exile.core.v2.Filter_Operator" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_tcnapi_exile_core_v2_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_tcnapi_exile_core_v2_entities_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Filter) GetOperator() Filter_Operator {
	if x != nil {
		return x.Operator
	}
	return Filter_EQUAL
}

var File_tcnapi_exile_core_v2_entities_proto protoreflect.FileDescriptor

const file_tcnapi_exile_core_v2_entities_proto_rawDesc = "" +
	"\n" +
	"#tcnapi/exile/core/v2/entities.proto\x12\x14tcnapi.exile.core.v2\"\xec\x01\n" +
	"\x04Pool\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12=\n" +
	"\x06status\x18\x03 \x01(\x0e2%.tcnapi.exile.core.v2.Pool.PoolStatusR\x06status\x12!\n" +
	"\frecord_count\x18\x04 \x01(\x03R\vrecordCount\"G\n" +
	"\n" +
	"PoolStatus\x12\t\n" +
	"\x05READY\x10\x00\x12\r\n" +
	"\tNOT_READY\x10\x01\x12\x11\n" +
	"\rNOT_AVAILABLE\x10\x01\x12\b\n" +
	"\x04BUSY\x10\x02\x1a\x02\x10\x01\"n\n" +
	"\x06Record\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12.\n" +
	"\x13json_record_payload\x18\x03 \x01(\tR\x11jsonRecordPayload\"}\n" +
	"\x05Field\x12\x17\n" +
	"\apool_id\x18\x03 \x01(\tR\x06poolId\x12\x1b\n" +
	"\trecord_id\x18\x04 \x01(\tR\brecordId\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x1f\n" +
	"\vfield_value\x18\x02 \x01(\tR\n" +
	"fieldValue\"\x8a\x01\n" +
	"\x06Filter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12A\n" +
	"\boperator\x18\x03 \x01(\x0e2%.tcnapi.exile.core.v2.Filter.OperatorR\boperator\"\x15\n" +
	"\bOperator\x12\t\n" +
	"\x05EQUAL\x10\x00B\xe7\x01\n" +
	"\x18com.tcnapi.exile.core.v2B\rEntitiesProtoP\x01ZIgithub.com/tcncloud/sati-go/internal/genproto/tcnapi/exile/core/v2;corev2\xa2\x02\x03TEC\xaa\x02\x14Tcnapi.Exile.Core.V2\xca\x02\x14Tcnapi\\Exile\\Core\\V2\xe2\x02 Tcnapi\\Exile\\Core\\V2\\GPBMetadata\xea\x02\x17Tcnapi::Exile::Core::V2b\x06proto3"

var (
	file_tcnapi_exile_core_v2_entities_proto_rawDescOnce sync.Once
	file_tcnapi_exile_core_v2_entities_proto_rawDescData []byte
)

func file_tcnapi_exile_core_v2_entities_proto_rawDescGZIP() []byte {
	file_tcnapi_exile_core_v2_entities_proto_rawDescOnce.Do(func() {
		file_tcnapi_exile_core_v2_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tcnapi_exile_core_v2_entities_proto_rawDesc), len(file_tcnapi_exile_core_v2_entities_proto_rawDesc)))
	})
	return file_tcnapi_exile_core_v2_entities_proto_rawDescData
}

var file_tcnapi_exile_core_v2_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tcnapi_exile_core_v2_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tcnapi_exile_core_v2_entities_proto_goTypes = []any{
	(Pool_PoolStatus)(0), // 0: tcnapi.exile.core.v2.Pool.PoolStatus
	(Filter_Operator)(0), // 1: tcnapi.exile.core.v2.Filter.Operator
	(*Pool)(nil),         // 2: tcnapi.exile.core.v2.Pool
	(*Record)(nil),       // 3: tcnapi.exile.core.v2.Record
	(*Field)(nil),        // 4: tcnapi.exile.core.v2.Field
	(*Filter)(nil),       // 5: tcnapi.exile.core.v2.Filter
}
var file_tcnapi_exile_core_v2_entities_proto_depIdxs = []int32{
	0, // 0: tcnapi.exile.core.v2.Pool.status:type_name -> tcnapi.exile.core.v2.Pool.PoolStatus
	1, // 1: tcnapi.exile.core.v2.Filter.operator:type_name -> tcnapi.exile.core.v2.Filter.Operator
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tcnapi_exile_core_v2_entities_proto_init() }
func file_tcnapi_exile_core_v2_entities_proto_init() {
	if File_tcnapi_exile_core_v2_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcnapi_exile_core_v2_entities_proto_rawDesc), len(file_tcnapi_exile_core_v2_entities_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tcnapi_exile_core_v2_entities_proto_goTypes,
		DependencyIndexes: file_tcnapi_exile_core_v2_entities_proto_depIdxs,
		EnumInfos:         file_tcnapi_exile_core_v2_entities_proto_enumTypes,
		MessageInfos:      file_tcnapi_exile_core_v2_entities_proto_msgTypes,
	}.Build()
	File_tcnapi_exile_core_v2_entities_proto = out.File
	file_tcnapi_exile_core_v2_entities_proto_goTypes = nil
	file_tcnapi_exile_core_v2_entities_proto_depIdxs = nil
}
